// This is generated by AI, just for reference

import { useEffect, useRef, useState } from "react";
import {
	type JourneyNode,
	journeyNodes,
} from "#/content/home/journey-nodes.ts";

const JourneyNodeVoyageItem = ({ node }: { node: JourneyNode }) => {
	const [isActive, setIsActive] = useState(false);
	const buttonRef = useRef<HTMLButtonElement>(null);
	const popRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		if (!isActive || !buttonRef.current || !popRef.current) return;

		const buttonRect = buttonRef.current.getBoundingClientRect();
		const popRect = popRef.current.getBoundingClientRect();
		const padding = 16;

		let left = buttonRect.left + buttonRect.width / 2;
		let top = buttonRect.top - popRect.height - 12;

		if (top < padding) {
			top = buttonRect.bottom + 12;
		}

		if (left + popRect.width / 2 > window.innerWidth - padding) {
			left = window.innerWidth - popRect.width / 2 - padding;
		}

		if (left - popRect.width / 2 < padding) {
			left = popRect.width / 2 + padding;
		}

		popRef.current.style.setProperty("--pop-left", `${left}px`);
		popRef.current.style.setProperty("--pop-top", `${top}px`);
	}, [isActive]);

	return (
		<li
			className="journey-node"
			style={
				{
					"--x": node.x,
					"--y": node.y,
					"--node-color": `var(--color-step-${node.step})`,
				} as React.CSSProperties
			}
		>
			<button
				ref={buttonRef}
				type="button"
				className={`journey-dot ${isActive ? "is-active" : ""}`}
				aria-expanded={isActive}
				aria-controls={`journey-week-${node.step}`}
				aria-label={node.ariaLabel}
				onClick={() => setIsActive(!isActive)}
				onBlur={(e) => {
					if (!e.currentTarget.contains(e.relatedTarget as Node)) {
						setIsActive(false);
					}
				}}
			>
				<span>{node.week}</span>
			</button>
			<div className="journey-label">
				<span className="journey-week">{`Week ${node.week}`}</span>
				<span className="journey-phase">{node.phase}</span>
			</div>
			<div
				ref={popRef}
				className="journey-pop"
				id={`journey-week-${node.step}`}
				aria-hidden={!isActive}
				role="dialog"
			>
				<div className="journey-pop-inner">
					<h3>{node.title}</h3>
					<p>{node.description}</p>
					<span className="journey-skill">{node.skill}</span>
				</div>
			</div>
		</li>
	);
};

export const JourneyNodesVoyagePaper = () => {
	return (
		<div className="voyage-paper hidden md:block">
			<svg className="journey-route" viewBox="0 0 1000 420" aria-hidden="true">
				<path
					className="journey-route-shadow"
					d="M70 318 C150 322 186 228 270 216 C344 205 345 325 432 300 C507 278 516 218 592 206 C684 191 694 120 772 133 C852 146 868 210 934 232"
				/>
				<path
					className="journey-route-thread"
					d="M68 320 C148 324 186 226 270 214 C344 204 344 325 432 298 C507 276 516 218 592 204 C684 190 696 118 772 132 C852 146 868 210 936 230"
				/>
				<path
					className="journey-route-main"
					pathLength="1"
					d="M70 318 C150 322 186 228 270 216 C344 205 345 325 432 300 C507 278 516 218 592 206 C684 191 694 120 772 133 C852 146 868 210 934 232"
				/>
			</svg>

			<ol className="journey-nodes" aria-label="Seven-week Voyage journey">
				{journeyNodes.map((node) => (
					<JourneyNodeVoyageItem key={node.step} node={node} />
				))}
			</ol>

			<style>{`
				.voyage-paper {
					position: relative;
					min-height: 510px;
					overflow: visible;
					border: 1px solid rgba(76, 81, 91, 0.12);
					border-radius: 28px;
					background:
						linear-gradient(180deg, rgba(255, 255, 255, 0.96), rgba(247, 248, 250, 0.96)),
						repeating-linear-gradient(0deg, rgba(227, 229, 235, 0.34) 0 1px, transparent 1px 34px);
					box-shadow: 0 32px 70px -46px rgba(64, 147, 109, 0.48), 0 18px 44px rgba(76, 81, 91, 0.14);
				}

				.journey-route {
					position: absolute;
					inset: 44px 34px 70px;
					width: calc(100% - 68px);
					height: calc(100% - 114px);
					overflow: visible;
					pointer-events: none;
				}

				.journey-route-shadow,
				.journey-route-main,
				.journey-route-thread {
					fill: none;
					stroke-linecap: round;
					stroke-linejoin: round;
					vector-effect: non-scaling-stroke;
				}

				.journey-route-shadow {
					stroke: rgba(22, 23, 26, 0.1);
					stroke-width: 12;
				}

				.journey-route-thread {
					stroke: rgba(132, 181, 212, 0.75);
					stroke-width: 2;
					stroke-dasharray: 10 14;
				}

				.journey-route-main {
					stroke: #40936d;
					stroke-width: 4;
					stroke-dasharray: 1;
					stroke-dashoffset: 1;
					animation: route-draw 1.15s cubic-bezier(0.22, 0.61, 0.36, 1) 0.18s forwards;
				}

				@keyframes route-draw {
					to {
						stroke-dashoffset: 0;
					}
				}

				.journey-nodes {
					position: absolute;
					inset: 0;
					margin: 0;
					padding: 0;
					list-style: none;
				}

				.journey-node {
					--node-color: #40936d;
					position: absolute;
					left: calc(var(--x) - 35px);
					top: calc(var(--y) - 35px);
					z-index: 2;
					width: 70px;
					height: 70px;
				}

				.journey-dot {
					position: relative;
					width: 70px;
					height: 70px;
					padding: 0;
					border: 0;
					border-radius: 50%;
					background: transparent;
					color: #fff;
					cursor: pointer;
					display: grid;
					place-items: center;
				}

				.journey-dot::before,
				.journey-dot::after {
					content: "";
					position: absolute;
					inset: 0;
					border-radius: inherit;
					transition: transform 0.2s ease, opacity 0.2s ease, box-shadow 0.2s ease;
				}

				.journey-dot::before {
					border: 2px solid var(--node-color);
					background: #fff;
					box-shadow: 0 0 0 8px rgba(255, 255, 255, 0.88), 0 8px 18px rgba(0, 0, 0, 0.14);
				}

				.journey-dot::after {
					inset: 13px;
					background: var(--node-color);
					box-shadow: inset 0 -8px 14px rgba(0, 0, 0, 0.12);
				}

				.journey-dot span {
					position: relative;
					z-index: 1;
					width: 42px;
					height: 42px;
					color: #fff;
					font-size: 0.98rem;
					font-weight: 800;
					line-height: 1;
					display: grid;
					place-items: center;
				}

				.journey-node:hover,
				.journey-node:focus-within,
				.journey-node.is-active {
					z-index: 8;
				}

				.journey-node:hover .journey-dot::before,
				.journey-node:focus-within .journey-dot::before,
				.journey-node.is-active .journey-dot::before {
					transform: scale(1.08);
					box-shadow: 0 0 0 10px rgba(255, 255, 255, 0.95), 0 16px 34px -18px var(--node-color);
				}

				.journey-node:hover .journey-dot::after,
				.journey-node:focus-within .journey-dot::after,
				.journey-node.is-active .journey-dot::after {
					transform: scale(0.92);
				}

				.journey-dot:focus-visible {
					outline: 3px solid rgba(64, 147, 109, 0.32);
					outline-offset: 8px;
				}

				.journey-label {
					position: absolute;
					left: 50%;
					top: calc(100% + 0.7rem);
					min-width: 145px;
					transform: translateX(-50%);
					text-align: center;
					pointer-events: auto;
				}

				.journey-node:nth-child(2) .journey-label,
				.journey-node:nth-child(4) .journey-label,
				.journey-node:nth-child(5) .journey-label {
					top: auto;
					bottom: calc(100% + 0.7rem);
				}

				.journey-week {
					display: block;
					color: var(--node-color);
					font-size: 0.72rem;
					font-weight: 800;
					text-transform: uppercase;
				}

				.journey-phase {
					display: block;
					margin-top: 0.08rem;
					color: #16171a;
					font-size: 0.9rem;
					font-weight: 800;
				}

				.journey-pop {
					position: fixed;
					left: var(--pop-left, 50vw);
					top: var(--pop-top, 50vh);
					z-index: 45;
					width: min(285px, calc(100vw - 32px));
					opacity: 0;
					visibility: hidden;
					transform: translate(-50%, 8px);
					pointer-events: none;
					transition: opacity 0.18s ease, transform 0.2s ease, visibility 0s linear 0.2s;
				}

				.journey-node:focus-within .journey-pop,
				.journey-node.is-active .journey-pop {
					opacity: 1;
					visibility: visible;
					transform: translate(-50%, 0);
					transition-delay: 0s;
					pointer-events: auto;
				}

				.journey-pop-inner {
					position: relative;
					padding: 1rem;
					border: 1px solid rgba(76, 81, 91, 0.14);
					border-left: 4px solid var(--node-color);
					border-radius: 12px;
					background: rgba(255, 255, 255, 0.97);
					box-shadow: 0 24px 44px -28px rgba(22, 23, 26, 0.42), 0 8px 20px rgba(76, 81, 91, 0.1);
				}

				.journey-pop-inner h3 {
					font-size: 1rem;
					font-weight: 700;
					margin: 0 0 0.5rem 0;
					color: #16171a;
				}

				.journey-pop-inner p {
					font-size: 0.875rem;
					font-weight: 500;
					margin: 0 0 0.75rem 0;
					color: #4c515b;
					line-height: 1.5;
				}

				.journey-skill {
					display: inline-block;
					margin-top: 0.75rem;
					padding: 0.5rem 0.75rem;
					border-radius: 6px;
					font-size: 0.7rem;
					font-weight: 700;
					text-transform: uppercase;
					background-color: color-mix(in srgb, var(--node-color) 10%, transparent);
					color: var(--node-color);
				}
			`}</style>
		</div>
	);
};
