import type { Meta, StoryObj } from "@storybook/tanstack-react";
import { TeamChatVisual } from "./team-chat-visual";

const meta = {
	title: "Components/Home/TeamChatVisual",
	component: TeamChatVisual,
	parameters: {
		layout: "centered",
		docs: {
			description: {
				component: "This component, and its associated css are generated by AI",
			},
		},
	},
	tags: ["autodocs"],
} satisfies Meta<typeof TeamChatVisual>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
	args: {},
};

export const InContainer: Story = {
	args: {},
	render: (args) => (
		<div className="bg-gradient-to-br from-blue-50 to-indigo-50 p-12 min-h-screen flex items-center justify-center">
			<TeamChatVisual {...args} />
		</div>
	),
};

export const Dark: Story = {
	args: {},
	render: (args) => (
		<div className="bg-gradient-to-br from-gray-900 to-gray-950 p-12 min-h-screen flex items-center justify-center">
			<TeamChatVisual {...args} />
		</div>
	),
};
