/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsVoyageXpRouteImport } from './routes/teams/voyage-xp'
import { Route as TeamsStandardVoyageRouteImport } from './routes/teams/standard-voyage'
import { Route as TeamsPairProgrammingRouteImport } from './routes/teams/pair-programming'
import { Route as RolesDevelopersRouteImport } from './routes/roles/developers'
import { Route as RolesDesignersRouteImport } from './routes/roles/designers'
import { Route as RolesAgileLeadersRouteImport } from './routes/roles/agile-leaders'
import { Route as CommunityWhyItsFreeRouteImport } from './routes/community/why-its-free'
import { Route as CommunityWhoRunsChinguRouteImport } from './routes/community/who-runs-chingu'
import { Route as CommunityAboutRouteImport } from './routes/community/about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsVoyageXpRoute = TeamsVoyageXpRouteImport.update({
  id: '/teams/voyage-xp',
  path: '/teams/voyage-xp',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsStandardVoyageRoute = TeamsStandardVoyageRouteImport.update({
  id: '/teams/standard-voyage',
  path: '/teams/standard-voyage',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsPairProgrammingRoute = TeamsPairProgrammingRouteImport.update({
  id: '/teams/pair-programming',
  path: '/teams/pair-programming',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesDevelopersRoute = RolesDevelopersRouteImport.update({
  id: '/roles/developers',
  path: '/roles/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesDesignersRoute = RolesDesignersRouteImport.update({
  id: '/roles/designers',
  path: '/roles/designers',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesAgileLeadersRoute = RolesAgileLeadersRouteImport.update({
  id: '/roles/agile-leaders',
  path: '/roles/agile-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityWhyItsFreeRoute = CommunityWhyItsFreeRouteImport.update({
  id: '/community/why-its-free',
  path: '/community/why-its-free',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityWhoRunsChinguRoute = CommunityWhoRunsChinguRouteImport.update({
  id: '/community/who-runs-chingu',
  path: '/community/who-runs-chingu',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAboutRoute = CommunityAboutRouteImport.update({
  id: '/community/about',
  path: '/community/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community/about': typeof CommunityAboutRoute
  '/community/who-runs-chingu': typeof CommunityWhoRunsChinguRoute
  '/community/why-its-free': typeof CommunityWhyItsFreeRoute
  '/roles/agile-leaders': typeof RolesAgileLeadersRoute
  '/roles/designers': typeof RolesDesignersRoute
  '/roles/developers': typeof RolesDevelopersRoute
  '/teams/pair-programming': typeof TeamsPairProgrammingRoute
  '/teams/standard-voyage': typeof TeamsStandardVoyageRoute
  '/teams/voyage-xp': typeof TeamsVoyageXpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community/about': typeof CommunityAboutRoute
  '/community/who-runs-chingu': typeof CommunityWhoRunsChinguRoute
  '/community/why-its-free': typeof CommunityWhyItsFreeRoute
  '/roles/agile-leaders': typeof RolesAgileLeadersRoute
  '/roles/designers': typeof RolesDesignersRoute
  '/roles/developers': typeof RolesDevelopersRoute
  '/teams/pair-programming': typeof TeamsPairProgrammingRoute
  '/teams/standard-voyage': typeof TeamsStandardVoyageRoute
  '/teams/voyage-xp': typeof TeamsVoyageXpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community/about': typeof CommunityAboutRoute
  '/community/who-runs-chingu': typeof CommunityWhoRunsChinguRoute
  '/community/why-its-free': typeof CommunityWhyItsFreeRoute
  '/roles/agile-leaders': typeof RolesAgileLeadersRoute
  '/roles/designers': typeof RolesDesignersRoute
  '/roles/developers': typeof RolesDevelopersRoute
  '/teams/pair-programming': typeof TeamsPairProgrammingRoute
  '/teams/standard-voyage': typeof TeamsStandardVoyageRoute
  '/teams/voyage-xp': typeof TeamsVoyageXpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community/about'
    | '/community/who-runs-chingu'
    | '/community/why-its-free'
    | '/roles/agile-leaders'
    | '/roles/designers'
    | '/roles/developers'
    | '/teams/pair-programming'
    | '/teams/standard-voyage'
    | '/teams/voyage-xp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community/about'
    | '/community/who-runs-chingu'
    | '/community/why-its-free'
    | '/roles/agile-leaders'
    | '/roles/designers'
    | '/roles/developers'
    | '/teams/pair-programming'
    | '/teams/standard-voyage'
    | '/teams/voyage-xp'
  id:
    | '__root__'
    | '/'
    | '/community/about'
    | '/community/who-runs-chingu'
    | '/community/why-its-free'
    | '/roles/agile-leaders'
    | '/roles/designers'
    | '/roles/developers'
    | '/teams/pair-programming'
    | '/teams/standard-voyage'
    | '/teams/voyage-xp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityAboutRoute: typeof CommunityAboutRoute
  CommunityWhoRunsChinguRoute: typeof CommunityWhoRunsChinguRoute
  CommunityWhyItsFreeRoute: typeof CommunityWhyItsFreeRoute
  RolesAgileLeadersRoute: typeof RolesAgileLeadersRoute
  RolesDesignersRoute: typeof RolesDesignersRoute
  RolesDevelopersRoute: typeof RolesDevelopersRoute
  TeamsPairProgrammingRoute: typeof TeamsPairProgrammingRoute
  TeamsStandardVoyageRoute: typeof TeamsStandardVoyageRoute
  TeamsVoyageXpRoute: typeof TeamsVoyageXpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/voyage-xp': {
      id: '/teams/voyage-xp'
      path: '/teams/voyage-xp'
      fullPath: '/teams/voyage-xp'
      preLoaderRoute: typeof TeamsVoyageXpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/standard-voyage': {
      id: '/teams/standard-voyage'
      path: '/teams/standard-voyage'
      fullPath: '/teams/standard-voyage'
      preLoaderRoute: typeof TeamsStandardVoyageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/pair-programming': {
      id: '/teams/pair-programming'
      path: '/teams/pair-programming'
      fullPath: '/teams/pair-programming'
      preLoaderRoute: typeof TeamsPairProgrammingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/developers': {
      id: '/roles/developers'
      path: '/roles/developers'
      fullPath: '/roles/developers'
      preLoaderRoute: typeof RolesDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/designers': {
      id: '/roles/designers'
      path: '/roles/designers'
      fullPath: '/roles/designers'
      preLoaderRoute: typeof RolesDesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/agile-leaders': {
      id: '/roles/agile-leaders'
      path: '/roles/agile-leaders'
      fullPath: '/roles/agile-leaders'
      preLoaderRoute: typeof RolesAgileLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/why-its-free': {
      id: '/community/why-its-free'
      path: '/community/why-its-free'
      fullPath: '/community/why-its-free'
      preLoaderRoute: typeof CommunityWhyItsFreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/who-runs-chingu': {
      id: '/community/who-runs-chingu'
      path: '/community/who-runs-chingu'
      fullPath: '/community/who-runs-chingu'
      preLoaderRoute: typeof CommunityWhoRunsChinguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/about': {
      id: '/community/about'
      path: '/community/about'
      fullPath: '/community/about'
      preLoaderRoute: typeof CommunityAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityAboutRoute: CommunityAboutRoute,
  CommunityWhoRunsChinguRoute: CommunityWhoRunsChinguRoute,
  CommunityWhyItsFreeRoute: CommunityWhyItsFreeRoute,
  RolesAgileLeadersRoute: RolesAgileLeadersRoute,
  RolesDesignersRoute: RolesDesignersRoute,
  RolesDevelopersRoute: RolesDevelopersRoute,
  TeamsPairProgrammingRoute: TeamsPairProgrammingRoute,
  TeamsStandardVoyageRoute: TeamsStandardVoyageRoute,
  TeamsVoyageXpRoute: TeamsVoyageXpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
