/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RolesDevelopersRouteImport } from './routes/roles/developers'
import { Route as RolesDesignersRouteImport } from './routes/roles/designers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesDevelopersRoute = RolesDevelopersRouteImport.update({
  id: '/roles/developers',
  path: '/roles/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesDesignersRoute = RolesDesignersRouteImport.update({
  id: '/roles/designers',
  path: '/roles/designers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/roles/designers': typeof RolesDesignersRoute
  '/roles/developers': typeof RolesDevelopersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/roles/designers': typeof RolesDesignersRoute
  '/roles/developers': typeof RolesDevelopersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/roles/designers': typeof RolesDesignersRoute
  '/roles/developers': typeof RolesDevelopersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/roles/designers' | '/roles/developers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/roles/designers' | '/roles/developers'
  id: '__root__' | '/' | '/roles/designers' | '/roles/developers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RolesDesignersRoute: typeof RolesDesignersRoute
  RolesDevelopersRoute: typeof RolesDevelopersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/developers': {
      id: '/roles/developers'
      path: '/roles/developers'
      fullPath: '/roles/developers'
      preLoaderRoute: typeof RolesDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/designers': {
      id: '/roles/designers'
      path: '/roles/designers'
      fullPath: '/roles/designers'
      preLoaderRoute: typeof RolesDesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RolesDesignersRoute: RolesDesignersRoute,
  RolesDevelopersRoute: RolesDevelopersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
